import Foundation

/// 세모이 키보드 약어 데이터
/// 키 문자는 정렬되어 있어야 함
enum SemoiAbbreviations {
    static let abbreviations: [String: String] = [
        "nqw": " 수 없",
        "nq": " 수 있",
        "cfk": "가게",
        "fgjkz": "가끔 ",
        "fgk": "가는 ",
        "au": "가능",
        "anu": "가능성",
        "gikx": "가득 ",
        "fkmx": "가락",
        "akmt": "가령 ",
        "bfkm": "가루",
        "fgkm": "가르",
        "fhsy": "가만히 ",
        "afko": "가방",
        "bfkn": "가수",
        "fgkn": "가스",
        "gknz": "가슴",
        "iks": "가운데",
        "efgjk": "가을",
        "akl": "가장 ",
        "aklr": "가정",
        "klt": "가져",
        ".klx": "귀족",
        "klvx": "가족",
        "dfkl": "가지",
        ".akl": "강조",
        "aklv": "각종",
        "fiks": "간단",
        "bfko": "간부",
        "eik": "갈등",
        "ikz": "감독",
        "fikz": "감동",
        "fknz": "감사",
        "fklrz": "감정",
        "klw": "갑자기 ",
        "afkm": "강력",
        "acfkl": "강제",
        "afklv": "강조",
        "fgkz": "같은 ",
        "jksz": "같이 ",
        "kz": "개념",
        "eko": "개발",
        "adfko": "개방",
        "dfkns": "개선",
        "afknr": "개성",
        "befjk": "개월",
        "dfklx": "개인적",
        "hkx": "개혁",
        "krsx": "객관적",
        "ikr": "거대",
        "gikrs": "거든",
        "gikrw": "거듭",
        "dkm": "거리",
        "bkor": "거부",
        "gjkr": "거의 ",
        "klq": "거짓",
        "dekl": "거칠",
        "klrx": "걱정",
        "eks": "건물",
        "eknr": "건설",
        "klsx": "건축",
        "egjkr": "걸음",
        "knrz": "검사",
        "gkrz": "검은 ",
        "klrz": "검찰",
        ".ik": "코드",
        "ikv": "검토",
        "ikqr": "것도 ",
        "gkr": "것은 ",
        "egkr": "것을 ",
        "cfik": "게다가 ",
        "bkt": "겨우 ",
        "bejkt": "겨울",
        "ek": "결과",
        "ekx": "결국",
        ".kms": "결론",
        "kmsv": "결론",
        "eknt": "결심",
        "eklt": "결정",
        "ehk": "결코 ",
        "ehks": "결혼",
        "ckt": "경계",
        "aknt": "경상",
        "ajk": "경우",
        "adfkl": "경쟁",
        "aklt": "경제",
        "aklrt": "경제적",
        "ekl": "경찰",
        "ghkt": "경향",
        "akrt": "경험",
        "cgk": "계급",
        ".cik": "계단",
        "cikv": "계단",
        ".ckns": "계산",
        "cknsv": "계산",
        ".knx": "공식",
        "knvx": "계속",
        "ckr": "계약",
        "ceklr": "계절",
        "cgkl": "계층",
        ".cdkx": "계획",
        "dkvx": "계획",
        "bkm": "고구려",
        "kw": "고급",
        ".su": "고는 ",
        "gsuv": "고는 ",
        "dfikv": "고대",
        "agik": "고등",
        ".km": "롭게 ",
        "kmtv": "고려",
        ".akn": "성공",
        "adfknv": "고생",
        "knr": "고서 ",
        ".aik": "고통",
        "aikv": "고통",
        "ahk": "고향",
        "exy": "골목",
        "aks": "공간",
        "akx": "공격",
        "akw": "공급",
        "aik": "공동",
        "ako": "공부",
        "afknv": "공사",
        "akns": "공산",
        "dknvx": "공식",
        "ajkw": "공업",
        "ajks": "공연",
        "afkl": "공장",
        ".ako": "공포",
        "akov": "공포",
        ".fkl": "과정",
        "fklv": "과정",
        "cfkl": "과제",
        "fklvx": "과학자",
        "klrvx": "과학적",
        ".fksx": "관객",
        "fksvx": "관객",
        "cfks": "관계",
        "fkls": "관계자",
        "ksz": "관념",
        "kmst": "관련",
        ".fkms": "관리",
        "fkmsv": "관리",
        "knz": "관심",
        "fjksx": "관악",
        ".fkls": "관점",
        "fklsv": "관점",
        "ekls": "관찰",
        "ak": "광고",
        "abfkl": "광주",
        "akls": "괜찮",
        ".adkl": "굉장",
        "adklv": "굉장",
        "fknr": "교사",
        "bkn": "교수",
        "jkx": "교육",
        "afklr": "교장",
        "afikr": "교통",
        "abkt": "구경",
        "bfk": "구나",
        "bik": "구두",
        "bgkm": "구름",
        "bkos": "구분",
        "knrx": "구석",
        "abkn": "구성",
        "bknx": "구속",
        "bkl": "구조",
        "ckl": "구체적",
        "kx": "국가",
        "bfkx": "국내",
        "ksx": "국민",
        "bcklx": "국제",
        "biks": "군대",
        "bfkns": "군사",
        "bgk": "궁금",
        "kmx": "권력",
        ".kmrs": "권리",
        "bkmrs": "권리",
        "dklvx": "귀족",
        ".bkl": "규정",
        "bklv": "규정",
        "ahks": "균형",
        "kq": "그것",
        ".k": "그곳",
        "gkv": "그곳",
        "eu": "그날",
        ".agu": "그냥 ",
        "gkt": "그녀",
        "gik": "그대",
        "gim": "그대로 ",
        "aiks": "그동안",
        "fgik": "그때",
        "dfkm": "그래",
        "gkm": "그래도 ",
        "kmr": "그래서 ",
        "kmz": "그램",
        "kmq": "그랬",
        "gkmr": "그러",
        "fkm": "그러나 ",
        "dmu": "그러니",
        "kmrt": "그러려고 ",
        "kmrst": "그러려면 ",
        "gmr": "그러므로 ",
        "kms": "그런 ",
        "ckm": "그런데 ",
        "kmrz": "그럼 ",
        ";kms": "그렇",
        "dgkl": "그렇지",
        "kmw": "그룹",
        "gkmq": "그릇",
        "dgkm": "그리",
        "kmv": "그리고 ",
        "gkmt": "그리하여 ",
        "dkmz": "그림",
        "fgklz": "그림자",
        "fgks": "그만",
        "ghyz": "그만큼",
        "gkl": "그저 ",
        "bgkl": "그중",
        "kox": "극복",
        "fgklx": "극장",
        "gkrs": "근거",
        "giks": "근데 ",
        "gkms": "근로",
        "bgks": "근무",
        "gkox": "근본적",
        "gjkrs": "근원",
        "gkls": "근처",
        "egkn": "글쎄",
        "fgkl": "글자",
        "gkoz": "금방 ",
        "jkz": "금융",
        "dgklz": "금지",
        ".cdk": "기계",
        "ckv": "기계",
        "ks": "기는 ",
        "dik": "기다",
        "dfik": "기대",
        "dikv": "기도",
        "ikx": "기독교",
        ".kmx": "기록",
        "kmvx": "기록",
        "gkmz": "기름",
        ".kos": "기본",
        "kosv": "기본",
        "dkox": "기본적",
        "dko": "기분",
        "dgko": "기쁨",
        "fkn": "기사",
        "adfkn": "기상",
        "ekn": "기술",
        "jkw": "기업",
        ".kls": "최근 ",
        "klsv": "기존",
        "bkls": "기준",
        "adkls": "긴장",
        "adklz": "김정",
        "dklz": "김치",
        ";kw": "깊은 ",
        ";jkw": "깊이",
        "eikx": "까닭",
        "dkl": "까지 ",
        "fgjkq": "깨끗",
        "eklw": "껍질",
        "cjkr": "께서 ",
        "dkmv": "꼬리",
        "bgjk": "꾸는 ",
        "jkqw": "끊임없",
        "cfu": "나게 ",
        "fgu": "나는 ",
        "fmu": "나라",
        "muz": "나름",
        "fuy": "나마 ",
        "duy": "나머지",
        "bfuy": "나무",
        "alu": "나중",
        "fiu": "나타",
        "dfnu": "낚시",
        "enu": "날씨",
        "fouz": "남부",
        "uz": "남성",
        ".lux": "남쪽",
        "luvx": "남쪽",
        "ouz": "남편",
        "fhsu": "남한",
        "efgu": "낮은 ",
        "su": "내년",
        ";su": "내놓",
        "dfgu": "내는 ",
        "dfmu": "내려",
        "bou": "내부",
        "aju": "내용",
        "deju": "내일",
        "dflu": "내지 ",
        "dfnuz": "냄새",
        "ruy": "너무 ",
        "ghru": "너희",
        "emu": "널리 ",
        "euw": "넓은 ",
        "juz": "넘어",
        "ux": "녀석",
        "istu": "년대",
        "aiu": "노동",
        "afiu": "노동자",
        ".mu": "노래",
        "muv": "노래",
        "mux": "노력",
        "djsu": "노인",
        "msu": "논리",
        "suy": "논문",
        ".jsu": "논의",
        "jsuv": "논의",
        "auy": "농민",
        "aou": "농부",
        ".anu": "농사",
        "anuv": "농사",
        "fsuy": "농산물",
        ".aju": "농업",
        "ajuv": "농업",
        ".hsu": "농촌",
        "hsuv": "농촌",
        ".ju": "오늘날",
        "gjuv": "높은 ",
        ";uw": "높이",
        "bfu": "누나",
        "esu": "눈길",
        "euy": "눈물",
        ";qu": "눈빛",
        "bfju": "눈앞",
        ".bnu": "뉴스",
        "bnuv": "뉴스",
        "djuz": "느낌",
        ".gu": "느냐? ",
        "fgsu": "는가",
        "fgiu": "는다. ",
        "isu": "는데",
        ".iu": "또는 ",
        "ciuv": "는데도 ",
        "lsu": "는지 ",
        "egju": "늘어",
        "amu": "능력",
        "dju": "니까",
        "diu": "니다. ",
        "fik": "다가",
        "fikv": "다고",
        "gisu": "다는 ",
        "dfiu": "다니",
        "is": "다른 ",
        "dim": "다리",
        ".in": "시도",
        "finv": "다소 ",
        "bfin": "다수",
        "dfin": "다시 ",
        "ai": "다양",
        "bfis": "다운 ",
        "iz": "다음",
        "ilz": "다짐",
        "ciks": "단계",
        "bins": "단순",
        "dhn": "단순히 ",
        "fils": "단지",
        "cfis": "단체",
        "efik": "달걀",
        "efim": "달라",
        "em": "달러",
        "eim": "달리",
        "aiz": "담당",
        "ioz": "담배",
        "ain": "당시",
        "ins": "당신",
        "ais": "당연",
        "afil": "당장",
        "iw": "대답",
        "dfim": "대로 ",
        "bfsy": "대문",
        "ios": "대부분",
        "dio": "대비",
        "afin": "대상",
        "dins": "대신",
        "abil": "대중",
        "dfilx": "대책",
        "cfil": "대체",
        "aim": "대통령",
        "fior": "대표",
        "fiorx": "대표적",
        "ix": "대학",
        "his": "대한",
        "hisx": "대한민국",
        "bfik": "더구나 ",
        "bikrs": "더군. ",
        "iru": "더니 ",
        "fimr": "더라. ",
        "ijx": "더욱 ",
        "ikrs": "던가? ",
        ".io": "비디오",
        "fiov": "도 불구하고 ",
        "imx": "도록 ",
        "inrv": "도서관",
        "inv": "도시",
        "ijz": "도움",
        "ijw": "도입",
        "filx": "도착",
        "dimw": "독립",
        "eijx": "독일",
        ".i": "독특",
        "giv": "독특",
        "adik": "동기",
        ".aiu": "동네",
        "aiuv": "동네",
        ".aim": "동료",
        "aimv": "동료",
        "adfin": "동생",
        ".ain": "동시",
        "ainv": "동시",
        "aijs": "동안",
        "ailx": "동작",
        ".ilx": "동쪽",
        "ilvx": "동쪽",
        "ikq": "되겠",
        "diuv": "되는 ",
        "cdiu": "되는데",
        "ijq": "되었",
        "giu": "드는 ",
        "gijr": "드디어 ",
        "fgim": "드라마",
        "gimr": "드러",
        "fgiks": "든가",
        "ils": "든지 ",
        "egir": "들어",
        "eis": "들은 ",
        "eij": "들의 ",
        "ei": "들이 ",
        "iq": "듯이 ",
        "agim": "등록",
        "agil": "등장",
        "fgij": "따뜻",
        "fim": "따라",
        "imr": "따라서 ",
        ".im": "라도 ",
        "imv": "따로 ",
        "dfimv": "때로 ",
        "ijs": "때문",
        "egijr": "떠들",
        "iuv": "또는 ",
        "dfinv": "또다시 ",
        "fhjs": "또한 ",
        "gikr": "뜨거운 ",
        "cfm": "라게 ",
        "fkmv": "라고",
        "fgm": "라는 ",
        "fimv": "라도 ",
        ".jm": "오래",
        "djmv": "라디오",
        "msty": "라면",
        "fjmr": "러시아",
        "jmr": "러운 ",
        "kmt": "려고 ",
        "mty": "려면 ",
        "jmt": "려운 ",
        ".mn": "서로 ",
        "mnv": "로서 ",
        "mnr": "로써 ",
        "bjms": "로운 ",
        "ckmv": "롭게 ",
        "bgm": "루는 ",
        "gmu": "르는 ",
        "dgmu": "리는 ",
        "ejmr": "리얼",
        "eguy": "마늘",
        "fmsy": "마련",
        "bfmy": "마루",
        "fmy": "마리",
        "fgy": "마을",
        "yz": "마음",
        "fly": "마자 ",
        "lry": "마저 ",
        "bfly": "마주 ",
        "flxy": "마지막",
        "flsy": "마찬가지",
        "dly": "마치 ",
        "lyz": "마침 ",
        "cuy": "만나게 ",
        "fgi": "만들",
        "sxy": "만약",
        "lsxy": "만족",
        "hyz": "만큼 ",
        ".fhy": "만화",
        "fhvy": "만화",
        "fgsy": "많은 ",
        "asy": "많이 ",
        "eny": "말씀",
        "aqy": "맛있",
        "gsuy": "맞는 ",
        "dfmxy": "매력",
        "bfy": "매우 ",
        "chy": "매체",
        "mry": "머리",
        "dnqy": "머릿속",
        "gry": "먹는 ",
        "lrsy": "먼저",
        "emy": "멀리 ",
        "lty": "며칠",
        "nsty": "면서 ",
        "amy": "명령",
        ".y": "모든 ",
        "gvy": "모든 ",
        ".my": "모래",
        "mvy": "모래",
        "guy": "모르는 ",
        "nwy": "모습",
        "ay": "모양",
        "nxy": "목소리",
        "nxyz": "목숨",
        ".lxy": "목적",
        "lvxy": "목적",
        "oxy": "목표",
        ".emy": "몰래 ",
        "emvy": "몰래 ",
        ".nwy": "몹시 ",
        "nvwy": "몹시 ",
        "bfi": "무대",
        "bmty": "무려 ",
        "btwy": "무렵",
        ";wy": "무릎",
        "bmy": "무리",
        "bfny": "무사",
        "nsy": "무슨 ",
        "bny": "무시",
        "qy": "무엇",
        "bty": "무역",
        "lrxy": "무척 ",
        "bgi": "문득 ",
        "blsy": "문자",
        "cly": "문제",
        "clyz": "문제점",
        "hxy": "문학",
        "sy": "문화",
        "bfhsy": "문화재",
        "befy": "물가",
        "esy": "물건",
        "msy": "물론 ",
        "bemy": "물리",
        ".nxy": "물속",
        "nvxy": "물속",
        "ey": "물질",
        "bchy": "물체",
        "gmy": "므로 ",
        "xy": "미국",
        "dfmy": "미래",
        "dmsy": "미련",
        "dmy": "미리 ",
        ".ny": "소문",
        "dnvy": "미소",
        "beny": "미술",
        "dhy": "미터",
        "lxy": "민족",
        "dlsy": "민주",
        "ably": "민중",
        ";yz": "믿음",
        "demy": "밀리",
        "kosz": "바깥",
        "egou": "바늘",
        "fio": "바다",
        "fiox": "바닥",
        "fmo": "바라",
        "moz": "바람",
        "moxz": "바람직",
        ".mo": "피로",
        "mov": "바로 ",
        "bfo": "바위",
        "dlo": "바지",
        "aio": "바탕",
        "foxy": "박물관",
        "fnox": "박사",
        "aox": "밖에 ",
        "fkos": "반갑",
        "dfios": "반대",
        ".ios": "반도",
        "fiosv": "반도",
        "gios": "반드시 ",
        "osy": "반면",
        "aflos": "반장",
        "fou": "받는 ",
        ";oz": "받아",
        "fgo": "받은 ",
        "efko": "발견",
        "eio": "발달",
        "efno": "발생",
        "elo": "발전",
        "eo": "발표",
        "befho": "발휘",
        "afoy": "방문",
        "ow": "방법",
        "afno": "방송",
        "anox": "방송국",
        "ano": "방식",
        "ajos": "방안",
        "loz": "방침",
        "dfko": "배경",
        "bfjo": "배우",
        "dfnox": "백성",
        "dflox": "백제",
        "lorz": "백화점",
        "gmoq": "버릇",
        "gnor": "버스",
        "lors": "번째",
        "enor": "벌써 ",
        "oz": "범위",
        ".dlo": "범죄",
        "dlov": "범죄",
        "morw": "법률",
        "josw": "법원",
        "low": "법칙",
        "joq": "벗어",
        "emot": "별로 ",
        "ajo": "병원",
        ".ko": "포기",
        "kov": "보고",
        ".fkos": "보관",
        "fkosv": "보관",
        "dfou": "보내",
        "dfosu": "보낸 ",
        ".ou": "보는 ",
        "ouv": "보는 ",
        "iov": "보다 ",
        ".alo": "보장",
        "aflov": "보장",
        ".aio": "보통",
        "aiov": "보통",
        "flow": "복잡",
        ".kox": "본격적",
        "kovx": "본격적",
        ".mos": "본래",
        "mosv": "본래",
        "delo": "본질",
        "bgko": "부끄",
        "bfio": "부담",
        "dfio": "부대",
        "biov": "부도",
        ".aios": "부동산",
        "aiosv": "부동산",
        "gio": "부드",
        ";eio": "부딪",
        "boy": "부모",
        "oyz": "부모님",
        "bosy": "부문",
        "os": "부분",
        "nos": "부산",
        "bno": "부상",
        ";ox": "부엌",
        "bflo": "부자",
        "abflo": "부장",
        "blor": "부정",
        "blox": "부족",
        "lor": "부처",
        "bfiox": "부탁",
        "bio": "부터 ",
        ".lox": "북쪽",
        "lovx": "북쪽",
        "hos": "북한",
        "aoy": "분명",
        "adoy": "분명히 ",
        "bnos": "분석",
        "kos": "분위기",
        ".fko": "불과",
        "fkov": "불과",
        "beko": "불교",
        "bko": "불구",
        "efoy": "불만",
        "eow": "불법",
        "eos": "불안",
        "ehos": "불편",
        "fkor": "비교",
        "fkorx": "비교적",
        "dgkox": "비극",
        "fosu": "비난",
        "eou": "비닐",
        "diov": "비디오",
        ".no": "소비자",
        "dnov": "비로소 ",
        "mox": "비록 ",
        "moq": "비롯",
        "eoy": "비밀",
        "noq": "비슷",
        "adko": "비행기",
        "emo": "빨리 ",
        "bmo": "뿌리",
        "cko": "쁘게 ",
        "fkns": "사건",
        ".kn": "수고",
        "knv": "사고",
        ".fkn": "사과",
        "fknv": "사과",
        "fnu": "사내",
        "fgn": "사는 ",
        "fmn": "사라",
        "nz": "사람",
        "amn": "사랑",
        ".cmn": "사례",
        "cmnv": "사례",
        "fny": "사무",
        "efny": "사물",
        "en": "사실",
        "jnw": "사업",
        "afln": "사장",
        "flnrs": "사전",
        "aflnr": "사정",
        "dlns": "사진",
        "fhn": "사회",
        "fhnx": "사회적",
        "jnsw": "산업",
        "elnx": "살짝 ",
        "eno": "살펴",
        "knxz": "삼국",
        "afkn": "상관",
        "afhn": "상당히 ",
        "adfio": "상대방",
        "adfinx": "상대적",
        "anx": "상식",
        "dfhn": "상태",
        "noz": "상품",
        ".afhn": "상황",
        "afhnv": "상황",
        "dfkn": "새끼",
        "dfmn": "새로 ",
        "dfmns": "새로운 ",
        "nox": "새벽",
        "efkn": "색깔",
        "knx": "생각",
        "any": "생명",
        "adfny": "생물",
        "ans": "생산",
        "ahn": "생활",
        "bknr": "서구",
        "gnr": "서는 ",
        "mnrv": "서로 ",
        "dgno": "서비스",
        "hnr": "서서히",
        "ejn": "서울",
        ".lnx": "지속",
        "lnrvx": "서쪽",
        "knrs": "선거",
        "ensy": "선물",
        "nors": "선배",
        "ns": "선생",
        "nuz": "선생님",
        "aflns": "선장",
        "blnr": "선진국",
        "inrs": "선택",
        "enry": "설명",
        "einr": "설탕",
        "akn": "성격",
        "aknr": "성경",
        "aknv": "성공",
        "amnr": "성령",
        "alnr": "성장",
        "alnx": "성적",
        "abdln": "성취",
        "acdln": "성취",
        "ckn": "세계",
        "cknx": "세계적",
        "cknz": "세금",
        "cdkn": "세기",
        "cin": "세대",
        "mnx": "세력",
        "an": "세상",
        "cfn": "세요",
        "cejnr": "세월",
        "chns": "센티",
        "dfknv": "소개",
        ".knz": "소금",
        "knvz": "소금",
        "ntu": "소녀",
        "nstu": "소년",
        "ginx": "소득",
        "mnst": "소련",
        "dmn": "소리",
        "nvy": "소문",
        "nov": "소비",
        "fnov": "소비자",
        ".n": "소스",
        "gnv": "소스",
        ".ln": "조사",
        "dflnv": "소재",
        "blnv": "소주",
        "abln": "소중",
        "cnor": "소프트웨어",
        "inx": "속도",
        ".kns": "신고",
        "knsv": "손가락",
        ".nsu": "손님",
        "nsuv": "손님",
        "eln": "솔직",
        "bknv": "수고",
        "fins": "수단",
        "bin": "수도",
        "bmn": "수록 ",
        "bdmn": "수리",
        "bfn": "수사",
        "abfn": "수상",
        "bfjn": "수요",
        "bln": "수준",
        "beln": "수출",
        "bhn": "수행",
        ".chn": "수혜",
        "chnv": "수혜",
        "bclnx": "숙제",
        "bkns": "순간",
        "bfln": "숫자",
        "knw": "쉽게 ",
        "gmnr": "스러",
        "gmnrs": "스러운 ",
        "mnw": "스럽",
        "gmn": "스스로",
        "fgin": "스타",
        "efgin": "스타일",
        "gin": "스트레스",
        "gno": "스포츠",
        "gknw": "습관",
        "nw": "습니다. ",
        "agmn": "승리",
        "dfknx": "시각",
        "kns": "시간",
        ".ckn": "시계",
        "cknv": "시계",
        ".ekn": "시골",
        "eknv": "시골",
        "dkn": "시기",
        "dnu": "시내",
        "dgnu": "시는 ",
        "fin": "시다. ",
        "din": "시대",
        "dinv": "시도",
        "dgln": "시리즈",
        "dny": "시민",
        "cinz": "시스템",
        "lnx": "시작",
        "aln": "시장",
        "el": "시절",
        "lnrz": "시점",
        "ahnr": "시청",
        "hnz": "시험",
        "dknx": "식구",
        "dinx": "식당",
        "dmnx": "식량",
        "dnxy": "식물",
        "nx": "식사",
        "dnox": "식품",
        "dkns": "신경",
        "dknsv": "신고",
        "mns": "신라",
        "dnsy": "신문",
        "enos": "신발",
        "dno": "신부",
        "dnos": "신분",
        "adlns": "신청",
        ".hns": "신호",
        "dhnsv": "신호",
        ".fhn": "신화",
        "fhnv": "신화",
        "denu": "실내",
        "adln": "실정",
        "deln": "실제",
        "dehn": "실천",
        "deno": "실패",
        "ehnz": "실험",
        "dknz": "심각",
        "dmnz": "심리",
        "alnz": "심장",
        ";nw": "싶은 ",
        "bfjnz": "싸움",
        "gnu": "쓰는 ",
        "gkn": "쓰레기",
        "nsu": "아나운서",
        "dfju": "아내",
        "fgjs": "아는 ",
        "fgj": "아들",
        "fjm": "아라",
        "dfjm": "아래",
        "fgjm": "아름",
        "bfj": "아무",
        "bfjq": "아무것",
        "bfim": "아무래도 ",
        "mrsy": "아무런 ",
        "bfm": "아무리",
        "flo": "아버지",
        "befj": "아울러",
        "lnr": "아저씨",
        "bfjl": "아주 ",
        "jlz": "아침",
        "fhj": "아파트",
        "ajsu": "안녕",
        "afgu": "않는 ",
        "afgj": "않은 ",
        "ejm": "알려",
        "fjwx": "압력",
        "efmy": "야말로 ",
        "jksx": "약간",
        "ajnx": "양식",
        "gjru": "어느 ",
        "fgju": "어느새 ",
        "js": "어떤 ",
        ";ijs": "어떻",
        "jmrtz": "어려움",
        "gjmr": "어른",
        "jmx": "어리석",
        "djms": "어린 ",
        "jru": "어머니",
        "cjlr": "어제",
        "gilr": "어쨌든 ",
        "lrt": "어쩌면 ",
        "jrsu": "언니",
        "jmrs": "언론",
        "cjlrs": "언제",
        "cjrs": "언제나 ",
        "cfjls": "언젠가 ",
        "ejk": "얼굴",
        "gjms": "얼른 ",
        "eju": "얼마나 ",
        "jkxz": "엄격",
        "ahjr": "엄청 ",
        "wy": "업무",
        "chj": "업체",
        "jquw": "없는 ",
        "jqruw": "없애는 ",
        "jqw": "없이 ",
        "cknr": "에게서 ",
        "clu": "에너지",
        "cfij": "에다 ",
        "cjnr": "에서 ",
        "cfj": "에요. ",
        "klrt": "여기저기",
        "mrt": "여러 ",
        "jort": "여러분",
        "jmst": "여론",
        "mz": "여름",
        "aj": "여성",
        "jlrt": "여전",
        "hjrt": "여전히 ",
        "jnx": "역사",
        "hjx": "역할",
        "ejks": "연결",
        "bjkt": "연구",
        "bknt": "연구소",
        "gjkt": "연극",
        "fjmx": "연락",
        "gjnt": "연습",
        "hjw": "연합",
        "ejnz": "열심",
        "bjt": "영국",
        "ajrt": "영양",
        "jrt": "영어",
        "jrst": "영원",
        "ahjt": "영향",
        "ahj": "영화",
        "cgjk": "예금",
        "cfjo": "예방",
        "cfjns": "예산",
        "acfjn": "예상",
        "jnz": "예수님",
        "cfjn": "예술가",
        ".cdj": "예외",
        "djv": "예외",
        "cjr": "예요. ",
        ".j": "예의",
        "gjv": "예의",
        "acjlr": "예정",
        "ejqu": "옛날",
        "jsu": "오는 ",
        "juv": "오늘",
        "fjuv": "오늘날",
        "jmv": "오래",
        "ajs": "오랫동안",
        ".lmx": "오른쪽",
        "lmvx": "오른쪽",
        ".hj": "해외",
        "bhjv": "오후",
        "hjv": "오히려 ",
        ";ejk": "온갖 ",
        ".ejm": "올라",
        "ejmv": "올라",
        ".mox": "폭력",
        "dmovx": "올림픽",
        "ehj": "올해",
        ".fhjs": "완전히 ",
        "fhjsv": "완전히 ",
        ".dfhu": "왜냐하면 ",
        "dfhuv": "왜냐하면 ",
        ".jksx": "외국인",
        "jksvx": "외국인",
        ".jlsx": "왼쪽",
        "jlsvx": "왼쪽",
        "bfjk": "요구",
        ".jk": "요금",
        "gjkv": "요금",
        "fgjlz": "요즘",
        "bju": "우는 ",
        "bmt": "우려",
        "bjm": "우리",
        "bfjns": "우산",
        "jns": "우선 ",
        "bgjn": "우승",
        "bjst": "우연",
        "aij": "운동",
        "bsty": "운명",
        "jxz": "움직",
        "jqz": "웃음",
        "dfjms": "원래",
        ".jmrs": "원리",
        "bjmrs": "원리",
        ".hjrs": "원한",
        "bhjrs": "원한",
        "bfjos": "위반",
        "abfjls": "위원장",
        "bdhjs": "위원회",
        "cdhjs": "위원회",
        "bdhj": "위치",
        "cdhj": "위치",
        "hjrz": "위험",
        "hjtw": "위협",
        "jmw": "유럽",
        ".bdjm": "유리",
        "bjmv": "인류",
        "abty": "유명",
        "fhjx": "유학",
        "bchjx": "육체",
        "dgju": "으니",
        "gjmt": "으려",
        "gjm": "으로 ",
        "gjt": "으며 ",
        "gjst": "으면 ",
        "cgij": "은데",
        "ghjs": "은행",
        "cgj": "은혜",
        "fgjk": "을까? ",
        "gjmz": "음료",
        "jz": "음식",
        "jx": "음악",
        "gjkst": "의견",
        ".ij": "의도",
        "gijv": "의도",
        "bgy": "의무",
        "bgj": "의문",
        ".jo": "의복",
        "gjov": "의복",
        "fgjn": "의사",
        "gjr": "의원",
        "fgjl": "의자",
        "fghj": "의학",
        "jkq": "이것",
        "fju": "이나 ",
        "efju": "이날",
        "jtu": "이념",
        "gju": "이는 ",
        "ekm": "이데올로기",
        "fjms": "이란",
        "djm": "이래",
        "ms": "이런 ",
        ";js": "이렇",
        "jms": "이론",
        "bjmx": "이룩",
        "jmz": "이름",
        "jos": "이번 ",
        "ajn": "이상",
        "jq": "이웃",
        "eghj": "이틀",
        "dhj": "이해",
        "bhj": "이후",
        "jks": "인간",
        "djsx": "인력",
        ".bjm": "인류",
        "ejs": "인물",
        "ajns": "인생",
        "jnsx": "인식",
        "ajls": "인정",
        "iqu": "인터넷",
        "eijs": "일단 ",
        "ejos": "일반",
        "elors": "일반적",
        "ejo": "일본",
        "ej": "일어",
        "ejl": "일정",
        "dehj": "일치",
        "jnsz": "임신",
        "jw": "입니다. ",
        "ejnw": "입술",
        "ajlw": "입장",
        "dhjw": "입학",
        "jqu": "있는 ",
        "aejq": "있을 ",
        "kltx": "자격",
        "gklx": "자극",
        "gklz": "자금",
        "fkl": "자기",
        "bfkl": "자꾸 ",
        "cflu": "자네",
        "ltu": "자녀",
        "fil": "자동차",
        "aflm": "자랑",
        "flm": "자료",
        "dlm": "자리",
        "lsty": "자면 ",
        ".los": "자본",
        "losv": "자본",
        "cln": "자세",
        "cfhn": "자세히 ",
        "fln": "자식",
        "lns": "자신",
        "jls": "자연",
        "bfjls": "자원",
        "befl": "자율",
        "fklrs": "자전거",
        "bfl": "자주 ",
        "cfl": "자체",
        "flos": "자판",
        "fklx": "작가",
        "lux": "작년",
        "jlw": "작업",
        "ajlx": "작용",
        "fgl": "작은 ",
        "lox": "작품",
        "fgil": "잔뜩",
        "lqy": "잘못",
        "klsz": "잠깐",
        "flnz": "잠시",
        "lw": "잡지",
        "afkls": "장관",
        "bfkls": "장군",
        "alsy": "장면",
        ".aln": "조상",
        "alnv": "장소",
        "dflm": "재료",
        "dfly": "재미",
        "eflor": "재벌",
        "dfln": "재산",
        "dflos": "재판",
        "lq": "저것",
        "klr": "저기",
        "lru": "저녁",
        ";lms": "저렇",
        "ghlr": "저희",
        "gklr": "적극",
        "gklrx": "적극적",
        "ilx": "적당",
        "ilrx": "적어도 ",
        "glm": "적으로 ",
        "lsx": "적인 ",
        "elx": "적절",
        "dfkls": "전개",
        "bklr": "전국",
        "dkls": "전기",
        "efil": "전달",
        ".ils": "전도",
        "ilrsv": "전도",
        "lms": "전략",
        "afly": "전망",
        "blrsy": "전문",
        "bfls": "전문가",
        "blors": "전부",
        "als": "전쟁",
        "clr": "전체",
        "clrx": "전체적",
        "ilrs": "전통",
        "ilrsx": "전통적",
        "flors": "전파",
        "hlrt": "전혀 ",
        "eil": "절대",
        "ejlz": "젊은",
        "dlnz": "점심",
        "klrw": "접근",
        ".lwx": "접촉",
        "lvwx": "접촉",
        ".klrs": "정권",
        "bklrs": "정권",
        "ailr": "정당",
        "al": "정도",
        "almr": "정리",
        "ely": "정말",
        ".lo": "정보",
        "lov": "정보",
        "alo": "정부",
        "alor": "정비",
        "alns": "정신",
        "gjlr": "정의",
        "hlx": "정책",
        "ahl": "정치",
        "ahlx": "정확",
        "cklr": "제거",
        "ackl": "제공",
        "dfil": "제대로 ",
        "cil": "제도",
        ".ly": "조미료",
        "clvy": "제목",
        "cdln": "제시",
        "cflx": "제작",
        "clo": "제품",
        "cfhls": "제한",
        "klrs": "조건",
        ".kl": "최고",
        "gklv": "조그",
        "lz": "조금",
        "dlvy": "조미료",
        "lnv": "조사",
        "aflnv": "조상",
        "lnrs": "조선",
        ".lnz": "조심",
        "dlnvz": "조심",
        "afhjr": "조용히 ",
        "lx": "조직",
        "hlw": "조합",
        "ls": "존재",
        "ejlw": "졸업",
        ".klv": "종교",
        "fklr": "종교",
        "alm": "종류",
        "ahlw": "종합",
        ";ls": "좋아",
        ".l": "좋은 ",
        "glv": "좋은 ",
        "bgl": "주는 ",
        "luz": "주님",
        "blm": "주로 ",
        "efly": "주말",
        "buy": "주머니",
        "blry": "주먹",
        "bly": "주민",
        "los": "주변",
        "blo": "주부",
        "blnx": "주식",
        "bgjl": "주의",
        ".akls": "주인공",
        "aklsv": "주인공",
        "abfl": "주장",
        "bilx": "주택",
        "jlxz": "죽음",
        "blos": "준비",
        "bekl": "줄기",
        "abkl": "중간",
        "klx": "중국",
        "bcln": "중세",
        "aklw": "중소기업",
        "lnz": "중심",
        "abfjl": "중앙",
        "ajl": "중요",
        "egkl": "즐거운 ",
        "afgkl": "증가",
        "agklr": "증거",
        "gklrs": "증권",
        "adkl": "지경",
        "klz": "지금",
        "dlu": "지나",
        "flsu": "지난 ",
        "deflu": "지난달",
        "dflsu": "지난해",
        "glsu": "지는 ",
        "dil": "지도",
        "lsy": "지만 ",
        "aflo": "지방",
        "dflo": "지배",
        "adfln": "지상",
        "lnvx": "지속",
        "dln": "지시",
        "dlnx": "지식",
        "jlx": "지역",
        "ehl": "지하철",
        ".cdl": "지혜",
        "clv": "지혜",
        "jlwx": "직업",
        "jlsx": "직원",
        "alx": "직장",
        "lwx": "직접 ",
        "lrwx": "직접적",
        "dils": "진단",
        "dlms": "진리",
        "elns": "진실",
        "els": "진출",
        "dely": "질문",
        "elnr": "질서",
        "ilw": "집단",
        "jlsw": "집안",
        "alw": "집중",
        "efgjl": "짧은 ",
        "dhm": "차라리 ",
        ".aglm": "차량",
        ".clm": "차례",
        "clmv": "차례",
        "elot": "차별",
        "hjs": "차원",
        "dfhj": "차이",
        "fklz": "참가",
        "dflnz": "참새",
        "lnrx": "참석",
        "fhjz": "참여",
        "aflsy": "창문",
        "fghu": "찾는 ",
        ";ejl": "찾아",
        "dflnx": "책상",
        "hjz": "책임",
        "lmz": "처럼 ",
        "lmr": "처리",
        "elor": "처벌",
        "hlz": "처음",
        "ehlx": "철학",
        "hrtu": "청년",
        ".hn": "청소",
        "hnv": "청소",
        "ahru": "청소년",
        ".il": "토지",
        "filv": "청와대",
        ".ckl": "체계",
        "cklv": "체계",
        "bchj": "체육",
        "chlr": "체험",
        "dklv": "초기",
        ".alm": "총리",
        "almv": "총리",
        "klv": "최고",
        "dklsv": "최근 ",
        ".dlns": "최소한",
        "dlnsv": "최소한",
        "bklx": "축구",
        "belo": "출발",
        "befhl": "출산",
        "ehls": "출신",
        "ejls": "출연",
        "aklx": "충격",
        "alos": "충분",
        "adlos": "충분히 ",
        "ghxy": "측면",
        "cdkl": "치게 ",
        "ghsu": "치는 ",
        ".lm": "치료",
        "dlmv": "치료",
        "dfhy": "치마",
        "kls": "친구",
        "dilz": "침대",
        "lmxz": "침략",
        "dhyz": "침묵",
        "cfhy": "카메라",
        "cfko": "카페",
        "fkms": "커다란 ",
        "kor": "커피",
        "hkz": "컴퓨터",
        "gikv": "코드",
        "cghk": "크게 ",
        "hsu": "키는 ",
        "dekm": "킬로",
        "dfinx": "택시",
        "cim": "텔레비전",
        ".ims": "토론",
        "imsv": "토론",
        "ilv": "토지",
        "ahis": "통신",
        ".ahj": "통일",
        "ahjv": "통일",
        ".ail": "통제",
        "acilv": "통제",
        "ahiw": "통합",
        "bfil": "투자",
        "bil": "투쟁",
        "iox": "특별",
        "ainx": "특성",
        "bgin": "특수",
        "ahix": "특정",
        "gilx": "특징",
        "hix": "특히 ",
        "hiqw": "틀림없",
        "dgio": "티브이",
        "jox": "파악",
        "ekot": "판결",
        "fios": "판단",
        "dfoy": "판매",
        "ior": "퍼센트",
        "dmo": "편리",
        "hjst": "편안",
        "lost": "편지",
        "akot": "평가",
        "akos": "평균",
        "adfno": "평생",
        "anot": "평소",
        "ajort": "평양",
        "dkov": "포기",
        "hoz": "포함",
        "movx": "폭력",
        ".ovy": "표면",
        "fory": "표면",
        "aho": "표정",
        "hort": "표현",
        "gko": "프게 ",
        "amo": "프랑스",
        "gmo": "프로",
        "dmov": "피로",
        "eho": "필요",
        "deflo": "필자",
        "cfh": "하게 ",
        "hkq": "하겠",
        "fhu": "하나",
        "huz": "하나님",
        "ghu": "하는 ",
        "chu": "하는데",
        "ehu": "하늘",
        "fhm": "하루",
        "hnq": "하셨",
        "dhns": "하신 ",
        ";hs": "하얗",
        "hjt": "하여 ",
        "hjq": "하였",
        "hls": "하지만 ",
        "hx": "학교",
        "hux": "학년",
        "hnx": "학생",
        "ahs": "한강",
        "cfhk": "한계",
        "hs": "한국",
        "fghk": "한글",
        "bfhis": "한두 ",
        "dfhjs": "한때",
        "hosx": "한복",
        "fhns": "한숨",
        "hlsz": "한참",
        "cfhi": "한테 ",
        "efhn": "할 수",
        "ehns": "할 수는 ",
        "eh": "할머니",
        "eflo": "할아버지",
        "hz": "함께 ",
        "hw": "합니다. ",
        "dfhmw": "합리",
        "ah": "항상 ",
        "hnrx": "해석",
        "dfhjv": "해외",
        "dfhnx": "핵심",
        "ahi": "행동",
        "ahox": "행복",
        "adfhn": "행사",
        "adfhj": "행위",
        "hmr": "허리",
        "chjr": "헤어",
        "hns": "현상",
        "hnst": "현실",
        "hnrst": "현실적",
        "ahls": "현장",
        "hrst": "현저",
        "hwx": "협력",
        "ahtu": "형님",
        "ahnt": "형사",
        "ahnrt": "형성",
        "ahnx": "형식",
        "chlt": "형제",
        "ahos": "형편",
        "afhm": "호랑이",
        ".hnx": "혹시 ",
        "hnvx": "혹시 ",
        ".hjx": "혹은 ",
        "hjvx": "혹은 ",
        ".fhm": "화려",
        "fhmv": "화려",
        "hsty": "화면",
        "defln": "화장실",
        ".flo": "화장품",
        "flov": "화장품",
        "cfhl": "화제",
        "ehnx": "확실",
        "hjsx": "확인",
        "hks": "환경",
        "ehi": "활동",
        "hiz": "회담",
        ".dhn": "회사",
        "dhnv": "회사",
        ".hjs": "회원",
        "dhjsv": "회원",
        ".dhj": "회의",
        "dhjv": "회의",
        "bfhos": "후반",
        "hms": "훈련",
        "ahm": "훌륭",
        "ehn": "훨씬 ",
        "hmz": "흐름",
        "aghy": "흥미",
        "bhsy": "흥미로운 ",
        "ahy": "희망",
    ]
}
